# Generated by Django 5.1.3 on 2025-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_article_date_remove_article_full_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Інгредієнти'),
        ),
        migrations.AlterField(
            model_name='article',
            name='instructions',
            field=models.JSONField(blank=True, default=list, verbose_name='Інструкції'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to='recipe_photos/', verbose_name='Фотографія рецепту'),
        ),
    ]
