# Generated by Django 5.1.3 on 2025-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_article_instructions_alter_article_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/', verbose_name='Фотографія рецепту'),
        ),
    ]
