# Generated by Django 5.1.6 on 2025-02-16 19:10

import django.db.models.deletion
from .. import models as recipes_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.TextField(verbose_name='Інгредієнти'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to=recipes_models.article_image_upload_to, verbose_name='Фотографія рецепту'),
        ),
        migrations.CreateModel(
            name='InstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipes_models.instruction_image_upload_to, verbose_name='Зображення інструкції')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_images', to='recipes.article')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст інструкції')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions_text', to='recipes.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
