# Generated by Django 5.1.6 on 2025-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_article_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionimage',
            name='step_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер кроку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructiontext',
            name='step_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер кроку'),
            preserve_default=False,
        ),
    ]
